# Generated by Django 3.2 on 2022-02-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='static/media/dummy-profile-pic-male.webp', null=True, upload_to='static/media/user/'),
        ),
    ]
