# Generated by Django 3.2 on 2022-02-19 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skilldun', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('slug', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_serial', models.CharField(max_length=24)),
                ('lecture_name', models.CharField(max_length=56)),
                ('duration', models.CharField(max_length=24)),
                ('description', models.TextField()),
                ('lecture', models.FileField(blank=True, null=True, upload_to='static/media/coursecurriculam/')),
                ('lecture_link', models.CharField(blank=True, max_length=56, null=True)),
                ('choice_1', models.CharField(max_length=32)),
                ('choice_2', models.CharField(max_length=32)),
                ('choice_3', models.CharField(max_length=32)),
                ('choice_4', models.CharField(max_length=32)),
                ('choices_answer', models.CharField(max_length=32)),
                ('lecture_type', models.IntegerField(choices=[(1, 'Video'), (2, 'Text'), (3, 'Quiz')], default=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=72)),
                ('slug', models.CharField(max_length=56)),
                ('thumbnail', models.ImageField(upload_to='static/media/post/')),
                ('caption', models.CharField(max_length=32)),
                ('summery', models.TextField()),
                ('requirements', models.TextField()),
                ('total_duration', models.CharField(max_length=24)),
                ('total_lectures', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('total_hearts', models.IntegerField(default=0)),
                ('total_quizes', models.IntegerField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('free_course', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('offer_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('priority', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('position', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('about', models.TextField()),
                ('achivement', models.TextField()),
                ('objective', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
                ('slug', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_link', models.CharField(max_length=72)),
                ('active', models.BooleanField(default=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.instructor')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilldun.socialmedia')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('review', models.IntegerField(default=5)),
                ('active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('review', models.IntegerField(default=5)),
                ('active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseQuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
                ('answer_text', models.CharField(max_length=32)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseitem')),
                ('course_curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursecurriculum')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courseitem',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.instructor'),
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varified', models.BooleanField(default=True)),
                ('verify_date', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='coursecurriculum',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseitem'),
        ),
    ]
