# Generated by Django 3.2 on 2022-02-20 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_eventbooking_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventitem'),
        ),
    ]
